{% set name = "textdistance" %}
{% set version = "4.6.2" %}
{% set sha256 = "01e1fbcf7b871eb8f41911d94f461b0b99cf8003384ee0e1c34ca5c1a7ab2ed0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - textdistance

about:
  home: https://github.com/orsinium/textdistance
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TextDistance – python library for comparing distance between two or more sequences by many algorithms.

  description: |
    TextDistance – python library for comparing distance between two or more sequences by many algorithms.
  doc_url: https://pypi.org/project/textdistance/#description
  dev_url: https://github.com/orsinium/textdistance

extra:
  recipe-maintainers:
    - cu8blank
    - andfoy
    - ccordoba12
