{% set name = "textdistance" %}
{% set version = "4.6.3" %}
{% set sha256 = "d6dabc50b4ea832cdcf0e1e6021bd0c7fcd9ade155888d79bb6a3c31fce2dc6f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - textdistance

about:
  home: https://github.com/orsinium/textdistance
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TextDistance – python library for comparing distance between two or more sequences by many algorithms.

  description: |
    TextDistance – python library for comparing distance between two or more sequences by many algorithms.
  doc_url: https://pypi.org/project/textdistance/#description
  dev_url: https://github.com/orsinium/textdistance

extra:
  recipe-maintainers:
    - cu8blank
    - andfoy
    - ccordoba12
